### ISSUE TITLE
what is the correct argument format for service /opencl_caffe/opencl_caffe_srv/run_inference?

### ISSUE THREAD

**Issue by StanleyYake** [intel/ros_opencl_caffe#12]
Hello there, Thanks for your work on opencl_caffe,I have a question.when I use 
`rosservice call /opencl_caffe/opencl_caffe_srv/run_inference "image_paths:/home/yake/catkin_ws/src/ros_opencl_caffe/opencl_caffe/resources/ 'cat.jpg'" `
ERROR: Incompatible arguments to call service:
Field [image_paths] must be a list or tuple instead of: str
Provided arguments are:image_paths:/home/yake/catkin_ws/src/ros_opencl_caffe/opencl_caffe/resources/ 'cat.jpg' (type str)
So what is the correct argument format for service, if you have any idea, happy to see your comment.

**Comment by chaoli2** [comment]
@StanleyYake 
Sorry for the late response. The correct argument format for service should be a list or tuple, like below command:
```
rosservice call /opencl_caffe/opencl_caffe_srv/run_inference "[/home/intel/catkin_ws/src/ros_opencl_caffe/opencl_caffe/resources/cat.jpg]"
```

**Comment by chaoli2** [comment]
Close this thread due to no response. Please re-open it if still any issue.
