### ISSUE TITLE
Linking error 

### ISSUE THREAD

**Issue by anaescesc** [intel/ros_opencl_caffe#13]
Hi!!,
I had followed the installation instructions and when I do catkin_make in workspace I get this error:

[ 93%] Linking CXX executable /home/caffe-cpu/catkin_ws/devel/lib/opencl_caffe/unittest_detector
CMakeFiles/opencl_caffe_srv.dir/src/detector_gpu.cpp.o: In function `int opencl_caffe::DetectorGpu::initNetwork<half_float::half>(std::shared_ptr<caffe::Net<half_float::half> >&, std::vector<half_float::half*, std::allocator<half_float::half*> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
detector_gpu.cpp:(.text._ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_[_ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_]+0x5f): undefined reference to `caffe::Net<half_float::half>::Net(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, caffe::Phase, caffe::device*, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*)'
detector_gpu.cpp:(.text._ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_[_ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_]+0xe3): undefined reference to `caffe::Net<half_float::half>::CopyTrainedLayersFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
detector_gpu.cpp:(.text._ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_[_ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_]+0x17a): undefined reference to `caffe::Blob<half_float::half>::Reshape(int, int, int, int)'
detector_gpu.cpp:(.text._ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_[_ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_]+0x182): undefined reference to `caffe::Net<half_float::half>::Reshape()'
detector_gpu.cpp:(.text._ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_[_ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_]+0x18a): undefined reference to `caffe::Blob<half_float::half>::mutable_cpu_data()'
detector_gpu.cpp:(.text._ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_[_ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_]+0x4a2): undefined reference to `caffe::Net<half_float::half>::Forward(half_float::half*)'
CMakeFiles/opencl_caffe_srv.dir/src/detector_gpu.cpp.o: In function `int opencl_caffe::DetectorGpu::inference<half_float::half>(std::shared_ptr<caffe::Net<half_float::half> >&, std::vector<half_float::half*, std::allocator<half_float::half*> >&, boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > >, object_msgs::ObjectsInBoxes_<std::allocator<void> >&)':
detector_gpu.cpp:(.text._ZN12opencl_caffe11DetectorGpu9inferenceIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EEN5boost10shared_ptrIN11sensor_msgs6Image_ISaIvEEEEERN11object_msgs15ObjectsInBoxes_ISK_EE[_ZN12opencl_caffe11DetectorGpu9inferenceIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EEN5boost10shared_ptrIN11sensor_msgs6Image_ISaIvEEEEERN11object_msgs15ObjectsInBoxes_ISK_EE]+0x2d3): undefined reference to `caffe::Net<half_float::half>::Forward(half_float::half*)'
/detector_gpu.cpp:home(/caffe.-text._ZN12opencl_caffe11DetectorGpu9inferenceIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EEN5boost10shared_ptrIN11sensor_msgs6Image_ISaIvEEEEERN11object_msgs15ObjectsInBoxes_ISK_EEcpu[/catkin_ws_ZN12opencl_caffe11DetectorGpu9inferenceIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EEN5boost10shared_ptrIN11sensor_msgs6Image_ISaIvEEEEERN11object_msgs15ObjectsInBoxes_ISK_EE/]devel+/0x347lib)/:libopencl_caffe_nodelet.so :undefined  undefinedreference  referenceto  to` caffe`:caffe::Blob:<Nethalf_float<:half_float::half:>half:>::cpu_data:(Reshape)( )const''

/home/caffe-cpu/catkin_ws/devel/lib/libopencl_caffe_nodelet.so: undefined reference to `caffe::Net<half_float::half>::Net(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, caffe::Phase, caffe::device*, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*)'
/home/caffe-cpu/catkin_ws/devel/lib/libopencl_caffe_nodelet.so: undefined reference to `caffe::Blob<half_float::half>::mutable_cpu_data()'
/home/caffe-cpu/catkin_ws/devel/lib/libopencl_caffe_nodelet.so: undefined reference to `caffe::Net<half_float::half>::CopyTrainedLayersFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/home/caffe-cpu/catkin_ws/devel/lib/libopencl_caffe_nodelet.so: undefined reference to `caffe::Blob<half_float::half>::Reshape(int, int, int, int)'
/home/caffe-cpu/catkin_ws/devel/lib/libopencl_caffe_nodelet.so: undefined reference to `caffe::Net<half_float::half>::Forward(half_float::half*)'
/home/caffe-cpu/catkin_ws/devel/lib/libopencl_caffe_nodelet.so: undefined reference to `caffe::Blob<half_float::half>::cpu_data() const'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
ros_opencl_caffe/opencl_caffe/CMakeFiles/unittest_detector.dir/build.make:211: recipe for target '/home/caffe-cpu/catkin_ws/devel/lib/opencl_caffe/unittest_detector' failed
ros_opencl_caffe/opencl_caffe/CMakeFiles/opencl_caffe_srv.dir/build.make:200: recipe for target '/home/caffe-cpu/catkin_ws/devel/lib/opencl_caffe/opencl_caffe_srv' failed
make[2]: *** [/home/caffe-cpu/catkin_ws/devel/lib/opencl_caffe/unittest_detector] Error 1
make[2]: *** [/home/caffe-cpu/catkin_ws/devel/lib/opencl_caffe/opencl_caffe_srv] Error 1
CMakeFiles/Makefile2:2889: recipe for target 'ros_opencl_caffe/opencl_caffe/CMakeFiles/opencl_caffe_srv.dir/all' failed
make[1]: *** [ros_opencl_caffe/opencl_caffe/CMakeFiles/opencl_caffe_srv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1706: recipe for target 'ros_opencl_caffe/opencl_caffe/CMakeFiles/unittest_detector.dir/all' failed
make[1]: *** [ros_opencl_caffe/opencl_caffe/CMakeFiles/unittest_detector.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

clCaffe, vienna, isaac,OPencl,  dependencies had been installed.
Others:
Ubuntu 16.04
ROS kinetic
CUDA and cuDNN not installed (no GPU)

Can you help me ?? 

Thanks!!

**Comment by chaoli2** [comment]
@anaescesc 
From the log you provided, the linking error occurs when linking caffe functions like caffe::Net::Net. If you didn't modify the CMakelists.txt of this project, these caffe functions should be linked from /opt/clCaffe/build/lib. 
So I think the problem may be the environment LD_LIBRARY_PATH. Would you check this by ```echo $LD_LIBRARY_PATH``` in the terminal you did "catkin_make"? The output should include /opt/clCaffe/build/lib. After that, make sure that the soft link "/opt/clCaffe" points to your \<clCaffe-path\>, which by default is "~/code/clCaffe".
If any of above output is not as expected, just setup environment again following README:
```  sudo ln -s <clCaffe-path> /opt/clCaffe```
```export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/clCaffe/build/lib```

**Comment by anaescesc** [comment]
Both LD_LIBRARY_PATH and opt link are correct. echo LD_LIBRARY_PATH result is :
` /opt/intel/lib/intel64:/opt/intel/mkl/lib/intel64_lin:/home/caffe-cpu/catkin_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/opt/clCaffe/build/lib`

And the opt link:
`lrwxrwxrwx 1 root root 33 jul  6 15:44 /opt/clCaffe -> /home/caffe-cpu/Libraries/clCaffe`

My directory is not code, the clCaffe is installed in /home/Libraries. 

Thanks :)


Update: I was finally able to compile the project. I followed the instructions with code and local folders. I still don't understand why I can't use a different location. 

Thanks for answering
