### ISSUE TITLE
Test pkg with custom SDD dataset

### ISSUE THREAD

**Issue by anaescesc** [intel/ros_opencl_caffe#14]
Hi !!, I have trained my custom dataset in SSD caffe. When I test my .caffemodel, deploy.txt and labels.txt with ros pkg I get the next error:
```
This network produces output detection_out
I0709 17:48:38.319583  3172 net.cpp:280] Network initialization done.
I0709 17:48:38.319587  3172 net.cpp:281] Memory required for data: 361219662
[ WARN] [1531151318.325699960]: unknown control 'focus_auto'

I0709 17:48:38.399741  3172 net.cpp:796] Ignoring source layer mbox_loss
[ INFO] [1531151319.459252517]: Load resources completely!
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[opencl_caffe_manager-2] process has died [pid 3172, exit code -6, cmd /opt/ros/kinetic/lib/nodelet/nodelet manager __name:=opencl_caffe_manager __log:=/home/caffe-cpu/.ros/log/8b25c6fe-838f-11e8-955b-e470b879f135/opencl_caffe_manager-2.log].
log file: /home/caffe-cpu/.ros/log/8b25c6fe-838f-11e8-955b-e470b879f135/opencl_caffe_manager-2*.log
[ INFO] [1531151329.492919386]: Bond broken, exiting
[opencl_caffe_nodelet-3] process has finished cleanly
```
It is possible what i'm trying to do ? Do I have to change the files??
Thanks !!

**Comment by chaoli2** [comment]
@anaescesc 
We've not tested other models on this project yet. This project is the ROS wrapper for [clcaffe](https://github.com/01org/caffe/wiki/clCaffe). So it is determined by [clcaffe ](https://github.com/01org/caffe/wiki/clCaffe) that which networks and models are supported. If you still failed after you followed all above procedures in the link, it is saying that clcaffe doesn't support this model.

**Comment by chaoli2** [comment]
Close this thread. Please re-open it if still any issue.
