### ISSUE TITLE
Failed to load nodelet [/opencl_caffe_nodelet]

### ISSUE THREAD

**Issue by magiccjae** [intel/ros_opencl_caffe#16]
Hi,

When I run `roslaunch opencl_caffe_launch realsense_viewer.launch`,
I am getting error message 

```
[ERROR] [1548834064.425749698]: Failed to load nodelet [/opencl_caffe_nodelet] of type [opencl_caffe/opencl_caffe_nodelet] even after refreshing the cache: Failed to load library /home/magiccjae/realsense_ws/install/lib//libopencl_caffe_nodelet.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libcaffe.so.1.0.0-rc5: cannot open shared object file: No such file or directory)
[ERROR] [1548834064.425794900]: The error before refreshing the cache was: Failed to load library /home/magiccjae/realsense_ws/install/lib//libopencl_caffe_nodelet.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libcaffe.so.1.0.0-rc5: cannot open shared object file: No such file or directory)
[FATAL] [1548834064.426047795]: Failed to load nodelet '/opencl_caffe_nodelet` of type `opencl_caffe/opencl_caffe_nodelet` to manager `opencl_caffe_manager'
```

It looks like between **lib** and **libopencl_caffe_nodlet.so**, there is double-slash **//**. However, I can't seem to locate where is it caused. Anyone had the same issue or know what is going on? 

Thanks in advance!

**Comment by chaoli2** [comment]
@magiccjae 
Does the **libopencl_caffe_nodelet.so** generated as the [cmake rule](https://github.com/intel/ros_opencl_caffe/blob/ad4724b40712a9971621d1d7821007c97d2a3301/opencl_caffe/CMakeLists.txt#L96) here? Will you try to locate it with below commands:
```
cd /home/magiccjae/realsense_ws
find -name "libopencl_caffe_nodelet.so"
```

**Comment by magiccjae** [comment]
@chaoli2 ,

Thanks for quick help! I tried different things myself and I was able to pass this issue by doing two things.

1. I didn't use `catkin_make install`. I ran `catkin_make` and used generated files.
2. I had to complete the steps from
https://github.com/01org/caffe/wiki/clCaffe#layer-fusion

After solving this issue, 
`roslaunch opencl_caffe_launch realsense_viewer.launch`
runs fine. However, it doesn't seem to be working properly. I can close this issue and open another issue since the issue is different from this. 

Thank you!

**Comment by Jiang1206** [comment]
I had to complete the steps from
https://github.com/01org/caffe/wiki/clCaffe#layer-fusion
```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
Is it all the steps before compiling and installing? I still get an error after finishing this.
