### ISSUE TITLE
Error: /opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clReleaseMemObject@OPENCL_1.0'

### ISSUE THREAD

**Issue by shijiwensjw** [intel/ros_opencl_caffe#5]
Hi all:
when I do catkin_make in my catkin workspace, I found out that there always be a error, output like this:
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clReleaseMemObject@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clSetEventCallback@OPENCL_1.1'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clReleaseCommandQueue@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clFinish@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clEnqueueWriteBuffer@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clSetKernelArg@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clCreateContext@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clReleaseProgram@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clGetPlatformInfo@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clEnqueueUnmapMemObject@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clCreateProgramWithSource@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clRetainContext@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clCreateCommandQueue@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clWaitForEvents@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clEnqueueReadBuffer@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clEnqueueNDRangeKernel@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clEnqueueMapBuffer@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clCreateImage@OPENCL_1.2'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clRetainProgram@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clCreateSubBuffer@OPENCL_1.1'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clRetainMemObject@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clGetProgramBuildInfo@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clReleaseKernel@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clReleaseEvent@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clCreateKernelsInProgram@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clCreateBuffer@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clEnqueueCopyBuffer@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clBuildProgram@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clGetKernelInfo@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clEnqueueTask@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clCreateProgramWithBinary@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clGetDeviceIDs@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clGetEventProfilingInfo@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clRetainCommandQueue@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clGetDeviceInfo@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clReleaseContext@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clEnqueueCopyBufferToImage@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clGetPlatformIDs@OPENCL_1.0'
/opt/clCaffe/build/lib/libcaffe.so: undefined reference to `clGetProgramInfo@OPENCL_1.0'

![Uploading Screenshot from 2018-03-06 20-51-53.png…]()
![Uploading Screenshot from 2018-03-06 20-52-20.png…]()
Can you tell me where is wrong and how can I solve this? It would be much appreciate if anyone could help me out

Thanks,
Steven

**Comment by xhuan28** [comment]
It seems opencl isn't installed correctly.
Could you please double check the installation steps: https://github.com/01org/caffe/wiki/clCaffe#opencl-drivers-for-intel-platforms-on-linux-for-both-ubuntu-and-centos ?

**Comment by shijiwensjw** [comment]
May be I installed the opencl in a wrong way. But I wonder is it required the Ubuntu kernel version?

**Comment by shijiwensjw** [comment]
The output like this:
/sbin/ldconfig.real: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.7 is not a symbolic link

/sbin/ldconfig.real: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.6 is not a symbolic link

Is it something wrong?
Thank you.

**Comment by dongx1x** [comment]
This project only support intel opencl, the output seems using cuda and cudnn.

**Comment by shijiwensjw** [comment]
So, how can I solve this problem? How to stop it using cuda and cudnn?
And which ubuntu kernel version should I use?
Thanks.

**Comment by dongx1x** [comment]
Kernel version and how to install Intel OpenCL can be found in http://registrationcenter-download.intel.com/akdlm/irc_nas/11396/intel-opencl-4.1-installation.pdf

**Comment by xhuan28** [comment]
I would like to close this issue if there are no future questions.
