### ISSUE TITLE
Network configuration file or weights file not found! & Failed to load nodelet '/opencl_caffe_nodelet`Error

### ISSUE THREAD

**Issue by fiorano10** [intel/ros_opencl_caffe#8]
I'm trying to launch the demo file for realsense viewer on the D415, on Ubuntu 16.04, and OpenCV 2.4.*. It successfully compiles, and installs but I keep getting this error

`
SUMMARY
========

PARAMETERS
 * /camera/realsense_ros_camera/accel_fps: 1000
 * /camera/realsense_ros_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense_ros_camera/align_depth: False
 * /camera/realsense_ros_camera/camera_aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense_ros_camera/camera_aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense_ros_camera/camera_aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense_ros_camera/camera_aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense_ros_camera/color_fps: 30
 * /camera/realsense_ros_camera/color_height: 480
 * /camera/realsense_ros_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense_ros_camera/color_width: 640
 * /camera/realsense_ros_camera/depth_fps: 30
 * /camera/realsense_ros_camera/depth_height: 480
 * /camera/realsense_ros_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense_ros_camera/depth_width: 640
 * /camera/realsense_ros_camera/enable_color: True
 * /camera/realsense_ros_camera/enable_depth: True
 * /camera/realsense_ros_camera/enable_fisheye: True
 * /camera/realsense_ros_camera/enable_imu: True
 * /camera/realsense_ros_camera/enable_infra1: True
 * /camera/realsense_ros_camera/enable_infra2: True
 * /camera/realsense_ros_camera/enable_pointcloud: False
 * /camera/realsense_ros_camera/enable_sync: False
 * /camera/realsense_ros_camera/fisheye_fps: 30
 * /camera/realsense_ros_camera/fisheye_height: 480
 * /camera/realsense_ros_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense_ros_camera/fisheye_width: 640
 * /camera/realsense_ros_camera/gyro_fps: 1000
 * /camera/realsense_ros_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense_ros_camera/infra1_fps: 30
 * /camera/realsense_ros_camera/infra1_height: 480
 * /camera/realsense_ros_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense_ros_camera/infra1_width: 640
 * /camera/realsense_ros_camera/infra2_fps: 30
 * /camera/realsense_ros_camera/infra2_height: 480
 * /camera/realsense_ros_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense_ros_camera/infra2_width: 640
 * /camera/realsense_ros_camera/json_file_path:
 * /camera/realsense_ros_camera/serial_no:
 * /opencl_caffe_manager/num_worker_threads: 8
 * /opencl_caffe_nodelet/labels_path: /opt/clCaffe/data...
 * /opencl_caffe_nodelet/net_config_path: /opt/clCaffe/mode...
 * /opencl_caffe_nodelet/weights_path: /opt/clCaffe/mode...
 * /rosdistro: kinetic
 * /rosversion: 1.12.12

NODES
  /camera/
    realsense_ros_camera (nodelet/nodelet)
    realsense_ros_camera_manager (nodelet/nodelet)
  /
    opencl_caffe_manager (nodelet/nodelet)
    opencl_caffe_nodelet (nodelet/nodelet)
    opencl_caffe_viewer (opencl_caffe_viewer/opencl_caffe_viewer)

auto-starting new master
process[master]: started with pid [7437]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 0f085d9e-3794-11e8-865b-00e84c68eb85
process[rosout-1]: started with pid [7450]
started core service [/rosout]
process[opencl_caffe_manager-2]: started with pid [7467]
process[opencl_caffe_nodelet-3]: started with pid [7468]
process[opencl_caffe_viewer-4]: started with pid [7469]
[ INFO] [1522796968.891268809]: Loading nodelet /opencl_caffe_nodelet of type opencl_caffe/opencl_caffe_nodelet to manager opencl_caffe_manager with the following remappings:
[ INFO] [1522796968.891463508]: /inference -> /opencl_caffe/inference
[ INFO] [1522796968.891550169]: /usb_cam/image_raw -> /camera/color/image_raw
process[camera/realsense_ros_camera_manager-5]: started with pid [7470]
[ INFO] [1522796968.897482920]: waitForService: Service [/opencl_caffe_manager/load_nodelet] has not been advertised, waiting...
process[camera/realsense_ros_camera-6]: started with pid [7483]
[ INFO] [1522796968.937513306]: Initializing nodelet with 8 worker threads.
[ INFO] [1522796968.940688372]: waitForService: Service [/opencl_caffe_manager/load_nodelet] is now available.
[ INFO] [1522796968.964249007]: Initializing nodelet with 4 worker threads.
[ INFO] [1522796969.011243679]: RealSense ROS v2.0.2
[ INFO] [1522796969.011330348]: Running with LibRealSense v2.10.2
**[ERROR] [1522796969.016139810]: Network configuration file or weights file not found!**
**[FATAL] [1522796969.016188560]: Load resource failed.
[FATAL] [1522796969.160083438]: Failed to load nodelet '/opencl_caffe_nodelet` of type `opencl_caffe/opencl_caffe_nodelet` to manager `opencl_caffe_manager'**
[ INFO] [1522796969.174145147]: getParameters...
[ INFO] [1522796969.217622514]: setupDevice...
[ INFO] [1522796969.217664527]: JSON file is not provided
[ INFO] [1522796969.217711284]: ROS Node Namespace: camera
[ INFO] [1522796969.217782448]: Device Name: Intel RealSense 415
[ INFO] [1522796969.217872447]: Device Serial No: 748512060537
[ INFO] [1522796969.217899555]: Device FW version: 05.08.15.00
[ INFO] [1522796969.217928046]: Device Product ID: 0AD3
[ INFO] [1522796969.217953624]: Enable PointCloud: Off
[ INFO] [1522796969.217979207]: Align Depth: Off
[ INFO] [1522796969.218003302]: Sync Mode: Off
[ INFO] [1522796969.218118972]: Device Sensors:
[ INFO] [1522796969.218168670]: Stereo Module was found.
[ INFO] [1522796969.218202483]: RGB Camera was found.
[ INFO] [1522796969.218274930]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1522796969.218304088]: (Gyro, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1522796969.218333509]: (Accel, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1522796969.218364227]: setupPublishers...
[ INFO] [1522796969.346669068]: setupStreams...
[ INFO] [1522796969.359823452]: depth stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1522796969.360190800]: infra1 stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1522796969.360509172]: infra2 stream is enabled - width: 640, height: 480, fps: 30
**[opencl_caffe_nodelet-3] process has died [pid 7468, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load opencl_caffe/opencl_caffe_nodelet opencl_caffe_manager /usb_cam/image_raw:=/camera/color/image_raw inference:=/opencl_caffe/inference __name:=opencl_caffe_nodelet __log:=/home/agr/.ros/log/0f085d9e-3794-11e8-865b-00e84c68eb85/opencl_caffe_nodelet-3.log].**
log file: /home/agr/.ros/log/0f085d9e-3794-11e8-865b-00e84c68eb85/opencl_caffe_nodelet-3*.log
[ INFO] [1522796969.375803646]: color stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1522796969.395390090]: publishStaticTransforms...
[ INFO] [1522796969.399338769]: RealSense Node Is Up!
[opencl_caffe_manager-2] process has died [pid 7467, exit code -11, cmd /opt/ros/kinetic/lib/nodelet/nodelet manager __name:=opencl_caffe_manager __log:=/home/agr/.ros/log/0f085d9e-3794-11e8-865b-00e84c68eb85/opencl_caffe_manager-2.log].
log file: /home/agr/.ros/log/0f085d9e-3794-11e8-865b-00e84c68eb85/opencl_caffe_manager-2*.log
^C[camera/realsense_ros_camera-6] killing on exit
[camera/realsense_ros_camera_manager-5] killing on exit
[opencl_caffe_viewer-4] killing on exit
[ INFO] [1522796979.804790901]: Interrupt Signal is received! Terminating RealSense Node...
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete`

**Comment by fiorano10** [comment]
I had to generate the fused_yolo.caffemodel file, by following the wiki [here](https://github.com/01org/caffe/wiki/clCaffe), and using this [issue](https://github.com/01org/caffe/issues/104)

**Comment by aditya2592** [comment]
Hi,

When I am running the model fuse script, I am getting the following error and weights file is not generated : 

Command : 
```
 python ../../../tools/inference-optimize/model_fuse.py --indefinition yolo_deploy.prototxt --outdefinition fused_yolo_deploy.prototxt --inmodel yolo.caffemodel --outmodel fused_yolo.caffemodel
```
Error :
```
std::exception
Traceback (most recent call last):
  File "../../../tools/inference-optimize/model_fuse.py", line 385, in <module>
    main(sys.argv)
  File "../../../tools/inference-optimize/model_fuse.py", line 382, in main
    generate_new_model(args)
  File "../../../tools/inference-optimize/model_fuse.py", line 376, in generate_new_model
    generate_weights(in_model, args)
  File "../../../tools/inference-optimize/model_fuse.py", line 262, in generate_weights
    caffe.set_device(0)
SystemError: NULL result without error in PyObject_Call
```
Also, Is it possible to use ros_opencl_caffe without the fused model ?

**Comment by aditya2592** [comment]
I was using CPU so had to comment these lines 

```
# caffe.set_device(0)
# caffe.set_mode_gpu()
```

**Comment by chaoli2** [comment]
@aditya2592 
GPU in this project is the integrated graphics inside Intel CPU, not Nvidia or any other external graphics. So could you please recover code and have a try again?
